--- # DELEGATE TO FUNCTION DEMO
- hosts: apacheweb
  user: test
  sudo: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Run a remote ping on the application server
      command: ping -c 4 sdas2
      delegate_to: 127.0.0.1
    - name: Install a package
      yum: pkg=lynx state=latest
