--- # GETURL MODULE EXAMPLE
- hosts: aptserver
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Get and download the INI file from the above host
      get_url: url=http://sdas4.mylabserver.com/mytest.ini dest=/home/test/mytest.ini mode=0440
