--- # GROUP MODULE EXAMPLE
- hosts: appserver
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Add a new group called newgroup
      group: name=newgroup state=present 
    - name: Remove the above group
      group: name=newgroup state=absent
