--- # HTPASSWD MODULE EXAMPLE
- hosts: aptserver
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install the python dependencies
      apt: name=python-passlib state=latest
    - name: Adding a user to web site authentication
      htpasswd: path=/etc/apache2/.htpasswd name=test2 password=password owner=test2 group=test2 mode=0640
    - name: Removing a user from web site authentication
      htpasswd: path=/etc/apache2/.htpasswd name=test2 state=absent
