--- # My First YAML Playbook for Ansible
- hosts: apacheweb
  #become: yes
  #become_user: test
  #become_method: sudo
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
  vars_files:
  - conf/copyright.yml
  - conf/webdefaults.yml
  vars_prompt:
  - name: pkg_name
    prompt: Install which package?
  tasks:
  - name: Install Apache Web Server
    action: yum name=httpd state=installed
    #async: 300
    #poll: 3
    notify: Restart HTTPD
  - name: Install Prompted Package
    action: yum name={{ pkg_name }} state=present
  handlers:
  - name: Restart HTTPD
    action: service name=httpd state=restarted
