--- # YUM MODULE EXAMPLE
- hosts: apacheweb
  remote_user: test
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
    - name: Installing Apache Web Server
      yum: name=httpd state=installed
    - name: Equivalent of YUM UPGRAGE
      yum: name=* state=latest
