- name: Install (RedHat/CentOS) Apache Web Server
  yum: name={{ redhat_apache }} state=latest
  when: ansible_os_family == 'RedHat'
- shell: systemctl status httpd
  register: result
  until: result.stdout.find("active (running)") != -1
  retries: 5
  delay: 5
- debug: var=result
#- debug: Need to install telnet
  #when: ansible_os_family == 'RedHat'
  #notify: InstallTelnet
