- name: Install the Web Server Package
  yum: name={{ apache_pkg }} state=latest
- name: Create the webserver directory
  file: path={{ apache_dir }} state=directory mode=0644
- name: Copy the Apache Configuration file to remote host
  copy: src=files/httpd.conf.template dest=/etc/httpd/conf/httpd.conf owner=root group=root mode=0644
- name: Create the vhost.d directory on the remote host
  file: path=/etc/httpd/vhost.d dtate=directory mode=0644
- name: Copy and untar the source for the site
  unarchive: src=files/sitecode.tar.gz dest={{ apache_dir }}
- name: Copy the default vhost configuration file
  copy: src=files/default.conf.template dest=/etc/httpd/vhost.d/default.conf owner=root group=root mode=0644
  notify:
    - StartHttpd
    - TestHttpd
    - DisplayResult
