--- # DB SERVER PLAYBOOK
- hosts: appserver
  user: test
  sudo: yes
  connection: ssh
  gather_facts: yes
  vars:
    dbserver_pkg: mariadb-server
    dbclient_pkg: mariadb
    dbserver_fqdn: sdas3.mylabserver.com
    dbinstalldir: /var/lib
    dbinstancename: MyDBTest
    dbdistribution: RedHat
    dbversion: 5.5.44
  tasks:
    - name: Install the MariaDB Server
      yum: name=mariadb-server state=latest
    - name: Install the MariaDB Client Utilities
      yum: name=mariadb state=latest
    - name: Start the DB Service
      service: name=mariadb state=started
    - pause: prompt='PLease run the mysql_secure_installation binary and then press ENTER for the playbook to continue'
    - name: Restart  the DB service
      service: name=mariadb state=restarted
    - name: Copy the remote database in order to restore
      copy: src=files/mysqlbkup.sql dest=/var/lib/mysqlbkup.sql owner=root group=root mode=0755
    - name: Create the remote database instance
      shel: mysqladmin -u root -p password123 create MyDBTest
    - name: Import the database backup to the live DB
      shell: mysql -u root -p password123 MyDBTest < /var/lib/mysqlbkup.sql
      register: result
    - debug: var=result
    - name: Add a backup CRON job to run every dat at midnight
      cron: name='DBBackup' minute='0' hour='0' job='mysqldump -u root -p password123 --databases MyDBTest > dbbkup.sql'
    - name: Run a quick SQL command to be sure everything was created and is working
      shell: mysql -u root -p password123 -e 'SHOW DATABASES;'
      register: mysqlresult
    - debug: var=mysqlresult
