--- # NFS SERVER PLAYBOOK
- hosts: appserver
  user: test
  sudo: yes
  connection: ssh
  gather_facts: yes
  vars: 
    distribution: RedHat
    nfsutils_pkg: nfs-utils
    nfsserver_service: nfs-server
    nfslock_service: nfs-lock
    nfsmap_service: nfs-idmap
    rpcbind_service: rpcbind
    export_path: /var/share
    client_path: /mnt/remote
  tasks:
    - name: Install the NFS Server and Utilities
      yum: name={{ nfsutils_pkg }} state=latest
    - name: Copy the export file to remote server
      copy: src=files/exports.template dest=/etc/exports owner=root group=root mode=0644
      notify:
        - StartServerServices
        - InstallClientPackages
        - CreateClientMount
        - ClientMountServerResource
  handlers:
    - name: StartServerServices
      service: name={{ item }} state=started
      with_items:
        - '{{ rpcbind_service }}'
        - '{{ nfsserver_service }}'
        - '{{ nfslock_service }}'
        - '{{ nfsmap_service }}'
    - name: InstallClientPackages
      yum: name=nfs-utils state=latest
      delegate_to: 127.0.0.1
      notify:
        - StartClientServices
    - name: StartClientServices
      service: name={{ item }} state=started
      with_items:
        - '{{ rpcbind_service }}'
        - '{{ nfslock_service }}'
        - '{{ nfsmap_service }}' 
      delegate_to: 127.0.0.1
    - name: CreateClientMount
      file: path={{ client_path }} state=directory mode=0755
      delegate_to: 127.0.0.1
    - name: ClientMountServerResource
      mount: name={{ client_path }} src={{ export_path }} fstype=nfs state=present
      delegate_to: 127.0.0.1

