- name: Install (RedHat/CentOS) Apache Web Server
  yum: name={{ redhat_apache }} state=latest
  when: ansible_os_family == 'RedHat'
  notify: Restart HTTPD
  ignore_errors: yes
- name: Install (Debian/Ubuntu) Apache Web Server
  apt: name={{ debian_apache }} state=latest
  when: ansible_os_family == 'Debian'
  notify: Restart Apache2
  ignore_errors: yes
#- debug: Need to install telnet
  #when: ansible_os_family == 'RedHat'
  #notify: InstallTelnet
