--- # Outline to Playbook Translation
- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: no
  tasks:
  - name: date/time stamp for when the playbook start
    command: /usr/bin/date
    register: timedate_start
  - debug: var=timedate_start
  - name: install the apache webserver
    yum: pkg=httpd state=latest
  - name: start apache webserver
    service: name=httpd enabled=yes state=started
  - name: verify that the web service is running
    command: systemctl status httpd
    register: result
  - debug: var=result
  - name: install client software - telnet
    yum: pkg=telnet state=latest
  - name: install client software - lynx
    yum: pkg=lynx state=latest
  - name: log all the packages installed on the system
    command: yum list installed
    register: installed_result
  - debug: var=installed_result
  - name: date/time stamp for when the playbook ends
    command: /usr/bin/date
    register: timedate_end
  - debug: var=timedate_end
  handlers:
  - name: Start HTTPD
    service: name=httpd state=restarted
