- name: InstallClientPackages
  yum: name=nfs-utils state=latest
  notify:
    - StartClientServices
- name: StartClientServices
  service: name={{ item }} state=started
  with_items:
    - '{{ rpcbind_service }}'
    - '{{ nfslock_service }}'
    - '{{ nfsmap_service }}'
- name: CreateClientMount
  file: path={{ client_path }} state=directory mode=0755
- name: ClientMountServerResource
  mount: name={{ client_path }} src={{ export_path }} fstype=nfs state=present
